# config.py
BOT_TOKEN = "6430806787:AAFUtB2ghRrhHjNft9qyOyTG3HTCGSX77R8"

PAIR_LIST = ["EURUSD", "GBPUSD", "USDJPY", "AUDCAD", "EURJPY"]
TIMEFRAME = "1m"
SIGNAL_INTERVAL = 180  # Every 3 mins
CONFIDENCE_THRESHOLD = 99.0  # Ultra accurate signal only